batch_size = 64
num_channels = 1
num_classes = 10
image_size = 28
noise_dim = 54
generator_in_channels = noise_dim + num_classes
discriminator_in_channels = num_channels + num_classes
increment = False
weight_path = 'save/cgan'
w2v_path = 'save/w2v'
npy_path = 'save/s2a.npy'
forder_path = '../TextCluster/output/file_order.txt'
# l2i_path = '../TextCluster/output/label2index.pkl'
i2l_path = '../TextCluster/output/index2label.npy'
