# -*- coding: utf-8 -*-
"""
Created on Sun Apr 23 23:14:42 2017

@author: Scrooge
"""

from __future__ import print_function
from keras.datasets import cifar10
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Convolution2D, MaxPooling2D
from keras.optimizers import SGD
from keras.utils import np_utils
#from keras.utils.vis_utils import plot_model
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

batch_size = 32
nb_classes = 10
nb_epoch = 20
data_augmentation = True

# input image dimensions
img_rows, img_cols = 32, 32
# the CIFAR10 images are RGB
img_channels = 3

# the data, shuffled and split between train and test sets
(X_train, y_train), (X_test, y_test) = cifar10.load_data()
print('X_train shape:', X_train.shape)
print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')

Y_train = np_utils.to_categorical(y_train, nb_classes)
Y_test = np_utils.to_categorical(y_test, nb_classes)

layers_def=[
        'conv',
#        'conv',
        'pool',
        'dropout',
        'conv',
#        'conv',
        'pool',
        'dropout',
        'flat',
        'dense',
        'dropout',
        'dense'
        ]
params=[
        [32,3,3,'same'],
#        [32,3,3,'valid'],
        [2,2],
        [0.25],
        [64,3,3,'same'],
#        [64,3,3,'valid'],
        [2,2],
        [0.25],
        [],
        [512],
        [0.5],
        [nb_classes]
        ]

model = Sequential()

for index in range(0,len(layers_def)):
    if(index==0):
        if(layers_def[index]=='conv'):
            model.add(Convolution2D(params[index][0], params[index][1], params[index][2], border_mode=params[index][3],input_shape=X_train.shape[1:]))
            model.add(Activation('relu'))
    elif(index==len(layers_def)-1):
        if(layers_def[index]=='dense'):
            model.add(Dense(params[index][0]))
            model.add(Activation('softmax'))
    else:
        if(layers_def[index]=='conv'):
            model.add(Convolution2D(params[index][0], params[index][1], params[index][2], border_mode=params[index][3]))
            model.add(Activation('relu'))
        elif(layers_def[index]=='pool'):
            model.add(MaxPooling2D(pool_size=(params[index][0], params[index][1])))
        elif(layers_def[index]=='dropout'):
            model.add(Dropout(params[index][0]))
        elif(layers_def[index]=='flat'):
            model.add(Flatten())
        elif(layers_def[index]=='dense'):
            model.add(Dense(params[index][0]))
            model.add(Activation('relu'))

#plot_model(model, to_file='cifar10-cnn.png')

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy',optimizer=sgd,metrics=['accuracy'])

score = model.evaluate(X_test, Y_test, verbose=0)
print('Test score:', score[0])
print('Test accuracy:', score[1])
model.save('cifar10-cnn-novice.h5')

X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255

print('Using real-time data augmentation.')

    # 这将做预处理和实时数据增加
datagen = ImageDataGenerator(
        featurewise_center=False,  # 在数据集上将输入平均值设置为0
        samplewise_center=False,  # 将每个样本均值设置为0
        featurewise_std_normalization=False,  # 将输入除以数据集的std
        samplewise_std_normalization=False,  # 将每个输入除以其std
        zca_whitening=False,  # 应用ZCA白化
        rotation_range=0,  # 在一个范围下随机旋转图像(degrees, 0 to 180)
        width_shift_range=0.1,  # 水平随机移位图像（总宽度的分数）
        height_shift_range=0.1,  # 随机地垂直移动图像（总高度的分数）
        horizontal_flip=True,  # 随机翻转图像
        vertical_flip=False)  # 随机翻转图像
    # 计算特征方向归一化所需的数量
    # (std, mean, and principal components if ZCA whitening is applied)
datagen.fit(X_train)
    # fit the model on the batches generated by datagen.flow()
history=model.fit_generator(datagen.flow(X_train, Y_train,batch_size=batch_size),samples_per_epoch=X_train.shape[0],nb_epoch=nb_epoch,validation_data=(X_test, Y_test))
history=history.history
acc=np.array(history['acc'])
np.save("acc.npy",acc)
loss=np.array(history['loss'])
np.save("loss.npy",loss)


score = model.evaluate(X_test, Y_test, verbose=0)
print('Test score:', score[0])
print('Test accuracy:', score[1])
model.save('cifar10-cnn-trained.h5')