# Generated by Django 4.2.2 on 2023-07-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, max_length='16', unique=True, verbose_name='作者名称')),
                ('sEXT', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='sEXT')),
                ('sNEU', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='sNEU')),
                ('sAGR', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='sAGR')),
                ('sCON', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='sCON')),
                ('sOPN', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='sOPN')),
                ('cEXT', models.BooleanField(verbose_name='cEXT')),
                ('cNEU', models.BooleanField(verbose_name='cNEU')),
                ('cAGR', models.BooleanField(verbose_name='cAGR')),
                ('cCON', models.BooleanField(verbose_name='cCON')),
                ('cOPN', models.BooleanField(verbose_name='cOPN')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prototype', models.TextField(db_index=True, max_length=64, unique=True, verbose_name='原型')),
                ('translated', models.TextField(blank=True, max_length=16, verbose_name='中文翻译')),
                ('explanation', models.TextField(blank=True, max_length=1024, verbose_name='释义')),
                ('part_of_speech', models.CharField(blank=True, max_length=16, verbose_name='词性')),
            ],
        ),
    ]
